const mongoose=require('mongoose')
const campaignSchema =new mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    category:{
        type:String,
        required:true
    },
     location:{
        type:String,
        required:true
    },
     beneficiary:{
        type:String,
        required:true
    },
    shortDescription:{
        type:String,
        required:true
    },
     longDescription:{
        type:String,
        required:true
    },
    goalAmount:{
        type:Number,
        required:true
    },
     minDonation:{
        type:Number,
        required:true
    },
     endDate:{
        type:Date,
        required:true
    },
    image:{
        type:String,
        required:true
    },
     documents:{
        type:Array,
        required:true
    },
    status:{
        type:String,
        default:"pending"
    },
    totalRaised:{
        type:Number,
        default:0
    },
    fundriserMail:{
        type:String,
        required:true
    },
    createdAt:{
        type:Date,
        default:Date.now
    }

})
const campaigns =mongoose.model("campaigns",campaignSchema)
module.exports =campaigns